// ISO 3166-1 Country Codes
export interface ISO3166Country {
    Name: string;
    TwoLetterCode: string;
    ThreeLetterCode: string;
    NumericCode: string;
}

export const ISO3166Countries: ISO3166Country[] = [
    // { Name: "Afghanistan", TwoLetterCode: "AF", ThreeLetterCode: "AFG", NumericCode: "004" },
    // { Name: "Albania", TwoLetterCode: "AL", ThreeLetterCode: "ALB", NumericCode: "008" },
    // { Name: "Algeria", TwoLetterCode: "DZ", ThreeLetterCode: "DZA", NumericCode: "012" },
    // { Name: "American Samoa", TwoLetterCode: "AS", ThreeLetterCode: "ASM", NumericCode: "016" },
    // { Name: "Andorra", TwoLetterCode: "AD", ThreeLetterCode: "AND", NumericCode: "020" },
    // { Name: "Angola", TwoLetterCode: "AO", ThreeLetterCode: "AGO", NumericCode: "024" },
    // { Name: "Anguilla", TwoLetterCode: "AI", ThreeLetterCode: "AIA", NumericCode: "660" },
    // { Name: "Antarctica", TwoLetterCode: "AQ", ThreeLetterCode: "ATA", NumericCode: "010" },
    // { Name: "Antigua and Barbuda", TwoLetterCode: "AG", ThreeLetterCode: "ATG", NumericCode: "028" },
    // { Name: "Argentina", TwoLetterCode: "AR", ThreeLetterCode: "ARG", NumericCode: "032" },
    // { Name: "Armenia", TwoLetterCode: "AM", ThreeLetterCode: "ARM", NumericCode: "051" },
    // { Name: "Aruba", TwoLetterCode: "AW", ThreeLetterCode: "ABW", NumericCode: "533" },
    // { Name: "Australia", TwoLetterCode: "AU", ThreeLetterCode: "AUS", NumericCode: "036" },
    // { Name: "Austria", TwoLetterCode: "AT", ThreeLetterCode: "AUT", NumericCode: "040" },
    // { Name: "Azerbaijan", TwoLetterCode: "AZ", ThreeLetterCode: "AZE", NumericCode: "031" },
    // { Name: "Bahamas", TwoLetterCode: "BS", ThreeLetterCode: "BHS", NumericCode: "044" },
    // { Name: "Bahrain", TwoLetterCode: "BH", ThreeLetterCode: "BHR", NumericCode: "048" },
    // { Name: "Bangladesh", TwoLetterCode: "BD", ThreeLetterCode: "BGD", NumericCode: "050" },
    // { Name: "Barbados", TwoLetterCode: "BB", ThreeLetterCode: "BRB", NumericCode: "052" },
    // { Name: "Belarus", TwoLetterCode: "BY", ThreeLetterCode: "BLR", NumericCode: "112" },
    // { Name: "Belgium", TwoLetterCode: "BE", ThreeLetterCode: "BEL", NumericCode: "056" },
    // { Name: "Belize", TwoLetterCode: "BZ", ThreeLetterCode: "BLZ", NumericCode: "084" },
    // { Name: "Benin", TwoLetterCode: "BJ", ThreeLetterCode: "BEN", NumericCode: "204" },
    // { Name: "Bermuda", TwoLetterCode: "BM", ThreeLetterCode: "BMU", NumericCode: "060" },
    // { Name: "Bhutan", TwoLetterCode: "BT", ThreeLetterCode: "BTN", NumericCode: "064" },
    // { Name: "Bolivia, Plurinational State of", TwoLetterCode: "BO", ThreeLetterCode: "BOL", NumericCode: "068" },
    // { Name: "Bonaire, Sint Eustatius and Saba", TwoLetterCode: "BQ", ThreeLetterCode: "BES", NumericCode: "535" },
    // { Name: "Bosnia and Herzegovina", TwoLetterCode: "BA", ThreeLetterCode: "BIH", NumericCode: "070" },
    // { Name: "Botswana", TwoLetterCode: "BW", ThreeLetterCode: "BWA", NumericCode: "072" },
    // { Name: "Bouvet Island", TwoLetterCode: "BV", ThreeLetterCode: "BVT", NumericCode: "074" },
    // { Name: "Brazil", TwoLetterCode: "BR", ThreeLetterCode: "BRA", NumericCode: "076" },
    // { Name: "British Indian Ocean Territory", TwoLetterCode: "IO", ThreeLetterCode: "IOT", NumericCode: "086" },
    // { Name: "Brunei Darussalam", TwoLetterCode: "BN", ThreeLetterCode: "BRN", NumericCode: "096" },
    // { Name: "Bulgaria", TwoLetterCode: "BG", ThreeLetterCode: "BGR", NumericCode: "100" },
    // { Name: "Burkina Faso", TwoLetterCode: "BF", ThreeLetterCode: "BFA", NumericCode: "854" },
    // { Name: "Burundi", TwoLetterCode: "BI", ThreeLetterCode: "BDI", NumericCode: "108" },
    // { Name: "Cabo Verde", TwoLetterCode: "CV", ThreeLetterCode: "CPV", NumericCode: "132" },
    // { Name: "Cambodia", TwoLetterCode: "KH", ThreeLetterCode: "KHM", NumericCode: "116" },
    // { Name: "Cameroon", TwoLetterCode: "CM", ThreeLetterCode: "CMR", NumericCode: "120" },
    // { Name: "Canada", TwoLetterCode: "CA", ThreeLetterCode: "CAN", NumericCode: "124" },
    // { Name: "Cayman Islands", TwoLetterCode: "KY", ThreeLetterCode: "CYM", NumericCode: "136" },
    // { Name: "Central African Republic", TwoLetterCode: "CF", ThreeLetterCode: "CAF", NumericCode: "140" },
    // { Name: "Chad", TwoLetterCode: "TD", ThreeLetterCode: "TCD", NumericCode: "148" },
    // { Name: "Chile", TwoLetterCode: "CL", ThreeLetterCode: "CHL", NumericCode: "152" },
    // { Name: "China", TwoLetterCode: "CN", ThreeLetterCode: "CHN", NumericCode: "156" },
    // { Name: "Christmas Island", TwoLetterCode: "CX", ThreeLetterCode: "CXR", NumericCode: "162" },
    // { Name: "Cocos (Keeling) Islands", TwoLetterCode: "CC", ThreeLetterCode: "CCK", NumericCode: "166" },
    // { Name: "Colombia", TwoLetterCode: "CO", ThreeLetterCode: "COL", NumericCode: "170" },
    // { Name: "Comoros", TwoLetterCode: "KM", ThreeLetterCode: "COM", NumericCode: "174" },
    // { Name: "Congo", TwoLetterCode: "CG", ThreeLetterCode: "COG", NumericCode: "178" },
    // { Name: "Congo, the Democratic Republic of the", TwoLetterCode: "CD", ThreeLetterCode: "COD", NumericCode: "180" },
    // { Name: "Cook Islands", TwoLetterCode: "CK", ThreeLetterCode: "COK", NumericCode: "184" },
    // { Name: "Costa Rica", TwoLetterCode: "CR", ThreeLetterCode: "CRI", NumericCode: "188" },
    // { Name: "Côte d'Ivoire", TwoLetterCode: "CI", ThreeLetterCode: "CIV", NumericCode: "384" },
    // { Name: "Croatia", TwoLetterCode: "HR", ThreeLetterCode: "HRV", NumericCode: "191" },
    // { Name: "Cuba", TwoLetterCode: "CU", ThreeLetterCode: "CUB", NumericCode: "192" },
    // { Name: "Curaçao", TwoLetterCode: "CW", ThreeLetterCode: "CUW", NumericCode: "531" },
    // { Name: "Cyprus", TwoLetterCode: "CY", ThreeLetterCode: "CYP", NumericCode: "196" },
    // { Name: "Czechia", TwoLetterCode: "CZ", ThreeLetterCode: "CZE", NumericCode: "203" },
    // { Name: "Denmark", TwoLetterCode: "DK", ThreeLetterCode: "DNK", NumericCode: "208" },
    // { Name: "Djibouti", TwoLetterCode: "DJ", ThreeLetterCode: "DJI", NumericCode: "262" },
    // { Name: "Dominica", TwoLetterCode: "DM", ThreeLetterCode: "DMA", NumericCode: "212" },
    // { Name: "Dominican Republic", TwoLetterCode: "DO", ThreeLetterCode: "DOM", NumericCode: "214" },
    // { Name: "Ecuador", TwoLetterCode: "EC", ThreeLetterCode: "ECU", NumericCode: "218" },
    // { Name: "Egypt", TwoLetterCode: "EG", ThreeLetterCode: "EGY", NumericCode: "818" },
    // { Name: "El Salvador", TwoLetterCode: "SV", ThreeLetterCode: "SLV", NumericCode: "222" },
    // { Name: "Equatorial Guinea", TwoLetterCode: "GQ", ThreeLetterCode: "GNQ", NumericCode: "226" },
    // { Name: "Eritrea", TwoLetterCode: "ER", ThreeLetterCode: "ERI", NumericCode: "232" },
    // { Name: "Estonia", TwoLetterCode: "EE", ThreeLetterCode: "EST", NumericCode: "233" },
    // { Name: "Eswatini", TwoLetterCode: "SZ", ThreeLetterCode: "SWZ", NumericCode: "748" },
    // { Name: "Ethiopia", TwoLetterCode: "ET", ThreeLetterCode: "ETH", NumericCode: "231" },
    // { Name: "Falkland Islands (Malvinas)", TwoLetterCode: "FK", ThreeLetterCode: "FLK", NumericCode: "238" },
    // { Name: "Farroe Islands", TwoLetterCode: "FO", ThreeLetterCode: "FRO", NumericCode: "234" },
    // { Name: "Fiji", TwoLetterCode: "FJ", ThreeLetterCode: "FJI", NumericCode: "242" },
    // { Name: "Finland", TwoLetterCode: "FI", ThreeLetterCode: "FIN", NumericCode: "246" },
    // { Name: "France", TwoLetterCode: "FR", ThreeLetterCode: "FRA", NumericCode: "250" },
    // { Name: "French Guiana", TwoLetterCode: "GF", ThreeLetterCode: "GUF", NumericCode: "254" },
    // { Name: "French Polynesia", TwoLetterCode: "PF", ThreeLetterCode: "PYF", NumericCode: "258" },
    // { Name: "French Southern Territories", TwoLetterCode: "TF", ThreeLetterCode: "ATF", NumericCode: "260" },
    // { Name: "Gabon", TwoLetterCode: "GA", ThreeLetterCode: "GAB", NumericCode: "266" },
    // { Name: "Gambia", TwoLetterCode: "GM", ThreeLetterCode: "GMB", NumericCode: "270" },
    // { Name: "Georgia", TwoLetterCode: "GE", ThreeLetterCode: "GEO", NumericCode: "268" },
    // { Name: "Germany", TwoLetterCode: "DE", ThreeLetterCode: "DEU", NumericCode: "276" },
    // { Name: "Ghana", TwoLetterCode: "GH", ThreeLetterCode: "GHA", NumericCode: "288" },
    // { Name: "Gibraltar", TwoLetterCode: "GI", ThreeLetterCode: "GIB", NumericCode: "292" },
    // { Name: "Greece", TwoLetterCode: "GR", ThreeLetterCode: "GRC", NumericCode: "300" },
    // { Name: "Greenland", TwoLetterCode: "GL", ThreeLetterCode: "GRL", NumericCode: "304" },
    // { Name: "Grenada", TwoLetterCode: "GD", ThreeLetterCode: "GRD", NumericCode: "308" },
    // { Name: "Guadeloupe", TwoLetterCode: "GP", ThreeLetterCode: "GLP", NumericCode: "312" },
    // { Name: "Guam", TwoLetterCode: "GU", ThreeLetterCode: "GUM", NumericCode: "316" },
    // { Name: "Guatemala", TwoLetterCode: "GT", ThreeLetterCode: "GTM", NumericCode: "320" },
    // { Name: "Guernsey", TwoLetterCode: "GG", ThreeLetterCode: "GGY", NumericCode: "831" },
    // { Name: "Guinea", TwoLetterCode: "GN", ThreeLetterCode: "GIN", NumericCode: "324" },
    // { Name: "Guinea-Bissau", TwoLetterCode: "GW", ThreeLetterCode: "GNB", NumericCode: "624" },
    // { Name: "Guyana", TwoLetterCode: "GY", ThreeLetterCode: "GUY", NumericCode: "328" },
    // { Name: "Haiti", TwoLetterCode: "HT", ThreeLetterCode: "HTI", NumericCode: "332" },
    // { Name: "Heard Island and McDonald Islands", TwoLetterCode: "HM", ThreeLetterCode: "HMD", NumericCode: "334" },
    // { Name: "Holy See", TwoLetterCode: "VA", ThreeLetterCode: "VAT", NumericCode: "336" },
    // { Name: "Honduras", TwoLetterCode: "HN", ThreeLetterCode: "HND", NumericCode: "340" },
    // { Name: "Hong Kong", TwoLetterCode: "HK", ThreeLetterCode: "HKG", NumericCode: "344" },
    // { Name: "Hungary", TwoLetterCode: "HU", ThreeLetterCode: "HUN", NumericCode: "348" },
    // { Name: "Iceland", TwoLetterCode: "IS", ThreeLetterCode: "ISL", NumericCode: "352" },
    // { Name: "India", TwoLetterCode: "IN", ThreeLetterCode: "IND", NumericCode: "356" },
    // { Name: "Indonesia", TwoLetterCode: "ID", ThreeLetterCode: "IDN", NumericCode: "360" },
    // { Name: "Iran, Islamic Republic of", TwoLetterCode: "IR", ThreeLetterCode: "IRN", NumericCode: "364" },
    // { Name: "Iraq", TwoLetterCode: "IQ", ThreeLetterCode: "IRQ", NumericCode: "368" },
    // { Name: "Ireland", TwoLetterCode: "IE", ThreeLetterCode: "IRL", NumericCode: "372" },
    // { Name: "Isle of Man", TwoLetterCode: "IM", ThreeLetterCode: "IMN", NumericCode: "833" },
    // { Name: "Israel", TwoLetterCode: "IL", ThreeLetterCode: "ISR", NumericCode: "376" },
    // { Name: "Italy", TwoLetterCode: "IT", ThreeLetterCode: "ITA", NumericCode: "380" },
    // { Name: "Jamaica", TwoLetterCode: "JM", ThreeLetterCode: "JAM", NumericCode: "388" },
    // { Name: "Japan", TwoLetterCode: "JP", ThreeLetterCode: "JPN", NumericCode: "392" },
    // { Name: "Jersey", TwoLetterCode: "JE", ThreeLetterCode: "JEY", NumericCode: "832" },
    // { Name: "Jordan", TwoLetterCode: "JO", ThreeLetterCode: "JOR", NumericCode: "400" },
    // { Name: "Kazakhstan", TwoLetterCode: "KZ", ThreeLetterCode: "KAZ", NumericCode: "398" },
    // { Name: "Kenya", TwoLetterCode: "KE", ThreeLetterCode: "KEN", NumericCode: "404" },
    // { Name: "Kiribati", TwoLetterCode: "KI", ThreeLetterCode: "KIR", NumericCode: "296" },
    // { Name: "Korea, Democratic People's Republic of", TwoLetterCode: "KP", ThreeLetterCode: "PRK", NumericCode: "408" },
    // { Name: "Korea, Republic of", TwoLetterCode: "KR", ThreeLetterCode: "KOR", NumericCode: "410" },
    // { Name: "Kuwait", TwoLetterCode: "KW", ThreeLetterCode: "KWT", NumericCode: "414" },
    // { Name: "Kyrgyzstan", TwoLetterCode: "KG", ThreeLetterCode: "KGZ", NumericCode: "417" },
    // { Name: "Lao People's Democratic Republic", TwoLetterCode: "LA", ThreeLetterCode: "LAO", NumericCode: "418" },
    // { Name: "Latvia", TwoLetterCode: "LV", ThreeLetterCode: "LVA", NumericCode: "428" },
    // { Name: "Lebanon", TwoLetterCode: "LB", ThreeLetterCode: "LBN", NumericCode: "422" },
    // { Name: "Lesotho", TwoLetterCode: "LS", ThreeLetterCode: "LSO", NumericCode: "426" },
    // { Name: "Liberia", TwoLetterCode: "LR", ThreeLetterCode: "LBR", NumericCode: "430" },
    // { Name: "Libya", TwoLetterCode: "LY", ThreeLetterCode: "LBY", NumericCode: "434" },
    // { Name: "Liechtenstein", TwoLetterCode: "LI", ThreeLetterCode: "LIE", NumericCode: "438" },
    // { Name: "Lithuania", TwoLetterCode: "LT", ThreeLetterCode: "LTU", NumericCode: "440" },
    // { Name: "Luxembourg", TwoLetterCode: "LU", ThreeLetterCode: "LUX", NumericCode: "442" },
    // { Name: "Macao", TwoLetterCode: "MO", ThreeLetterCode: "MAC", NumericCode: "446" },
    // { Name: "Madagascar", TwoLetterCode: "MG", ThreeLetterCode: "MDG", NumericCode: "450" },
    // { Name: "Malawi", TwoLetterCode: "MW", ThreeLetterCode: "MWI", NumericCode: "454" },
    // { Name: "Malaysia", TwoLetterCode: "MY", ThreeLetterCode: "MYS", NumericCode: "458" },
    // { Name: "Maldives", TwoLetterCode: "MV", ThreeLetterCode: "MDV", NumericCode: "462" },
    // { Name: "Mali", TwoLetterCode: "ML", ThreeLetterCode: "MLI", NumericCode: "466" },
    // { Name: "Malta", TwoLetterCode: "MT", ThreeLetterCode: "MLT", NumericCode: "470" },
    // { Name: "Marshall Islands", TwoLetterCode: "MH", ThreeLetterCode: "MHL", NumericCode: "584" },
    // { Name: "Martinique", TwoLetterCode: "MQ", ThreeLetterCode: "MTQ", NumericCode: "474" },
    // { Name: "Mauritania", TwoLetterCode: "MR", ThreeLetterCode: "MRT", NumericCode: "478" },
    // { Name: "Mauritius", TwoLetterCode: "MU", ThreeLetterCode: "MUS", NumericCode: "480" },
    // { Name: "Mayotte", TwoLetterCode: "YT", ThreeLetterCode: "MYT", NumericCode: "175" },
    // { Name: "Mexico", TwoLetterCode: "MX", ThreeLetterCode: "MEX", NumericCode: "484" },
    // { Name: "Micronesia, Federated States of", TwoLetterCode: "FM", ThreeLetterCode: "FSM", NumericCode: "583" },
    // { Name: "Moldova, Republic of", TwoLetterCode: "MD", ThreeLetterCode: "MDA", NumericCode: "498" },
    // { Name: "Monaco", TwoLetterCode: "MC", ThreeLetterCode: "MCO", NumericCode: "492" },
    // { Name: "Mongolia", TwoLetterCode: "MN", ThreeLetterCode: "MNG", NumericCode: "496" },
    // { Name: "Montenegro", TwoLetterCode: "ME", ThreeLetterCode: "MNE", NumericCode: "499" },
    // { Name: "Montserrat", TwoLetterCode: "MS", ThreeLetterCode: "MSR", NumericCode: "500" },
    // { Name: "Morocco", TwoLetterCode: "MA", ThreeLetterCode: "MAR", NumericCode: "504" },
    // { Name: "Mozambique", TwoLetterCode: "MZ", ThreeLetterCode: "MOZ", NumericCode: "508" },
    // { Name: "Myanmar", TwoLetterCode: "MM", ThreeLetterCode: "MMR", NumericCode: "104" },
    // { Name: "Namibia", TwoLetterCode: "NA", ThreeLetterCode: "NAM", NumericCode: "516" },
    // { Name: "Nauru", TwoLetterCode: "NR", ThreeLetterCode: "NRU", NumericCode: "520" },
    // { Name: "Nepal", TwoLetterCode: "NP", ThreeLetterCode: "NPL", NumericCode: "524" },
    // { Name: "Netherlands", TwoLetterCode: "NL", ThreeLetterCode: "NLD", NumericCode: "528" },
    // { Name: "New Caledonia", TwoLetterCode: "NC", ThreeLetterCode: "NCL", NumericCode: "540" },
    // { Name: "New Zealand", TwoLetterCode: "NZ", ThreeLetterCode: "NZL", NumericCode: "554" },
    // { Name: "Nicaragua", TwoLetterCode: "NI", ThreeLetterCode: "NIC", NumericCode: "558" },
    // { Name: "Nier", TwoLetterCode: "NE", ThreeLetterCode: "NER", NumericCode: "562" },
    { Name: "Nigeria", TwoLetterCode: "NG", ThreeLetterCode: "NGA", NumericCode: "566" },
    // { Name: "Niue", TwoLetterCode: "NU", ThreeLetterCode: "NIU", NumericCode: "570" },
    // { Name: "Norfolk Island", TwoLetterCode: "NF", ThreeLetterCode: "NFK", NumericCode: "574" },
    // { Name: "Northern Mariana Islands", TwoLetterCode: "MP", ThreeLetterCode: "MNP", NumericCode: "580" },
    // { Name: "North Macedonia", TwoLetterCode: "MK", ThreeLetterCode: "MKD", NumericCode: "807" },
    // { Name: "Norway", TwoLetterCode: "NO", ThreeLetterCode: "NOR", NumericCode: "578" },
    // { Name: "Oman", TwoLetterCode: "OM", ThreeLetterCode: "OMN", NumericCode: "512" },
    // { Name: "Pakistan", TwoLetterCode: "PK", ThreeLetterCode: "PAK", NumericCode: "586" },
    // { Name: "Palau", TwoLetterCode: "PW", ThreeLetterCode: "PLW", NumericCode: "585" },
    // { Name: "Palestine, State of", TwoLetterCode: "PS", ThreeLetterCode: "PSE", NumericCode: "275" },
    // { Name: "Panama", TwoLetterCode: "PA", ThreeLetterCode: "PAN", NumericCode: "591" },
    // { Name: "Papua New Guinea", TwoLetterCode: "PG", ThreeLetterCode: "PNG", NumericCode: "598" },
    // { Name: "Paraguay", TwoLetterCode: "PY", ThreeLetterCode: "PRY", NumericCode: "600" },
    // { Name: "Peru", TwoLetterCode: "PE", ThreeLetterCode: "PER", NumericCode: "604" },
    // { Name: "Philippines", TwoLetterCode: "PH", ThreeLetterCode: "PHL", NumericCode: "608" },
    // { Name: "Pitcairn", TwoLetterCode: "PN", ThreeLetterCode: "PCN", NumericCode: "612" },
    // { Name: "Poland", TwoLetterCode: "PL", ThreeLetterCode: "POL", NumericCode: "616" },
    // { Name: "Portugal", TwoLetterCode: "PT", ThreeLetterCode: "PRT", NumericCode: "620" },
    // { Name: "Puerto Rico", TwoLetterCode: "PR", ThreeLetterCode: "PRI", NumericCode: "630" },
    // { Name: "Qatar", TwoLetterCode: "QA", ThreeLetterCode: "QAT", NumericCode: "634" },
    // { Name: "Réunion", TwoLetterCode: "RE", ThreeLetterCode: "REU", NumericCode: "638" },
    // { Name: "Romania", TwoLetterCode: "RO", ThreeLetterCode: "ROU", NumericCode: "642" },
    // { Name: "Russian Federation", TwoLetterCode: "RU", ThreeLetterCode: "RUS", NumericCode: "643" },
    // { Name: "Rwanda", TwoLetterCode: "RW", ThreeLetterCode: "RWA", NumericCode: "646" },
    // { Name: "Saint Barthélemy", TwoLetterCode: "BL", ThreeLetterCode: "BLM", NumericCode: "652" },
    // { Name: "Saint Helena, Ascension and Tristan da Cunha", TwoLetterCode: "SH", ThreeLetterCode: "SHN", NumericCode: "654" },
    // { Name: "Saint Kitts and Nevis", TwoLetterCode: "KN", ThreeLetterCode: "KNA", NumericCode: "659" },
    // { Name: "Saint Lucia", TwoLetterCode: "LC", ThreeLetterCode: "LCA", NumericCode: "662" },
    // { Name: "Saint Martin (French part)", TwoLetterCode: "MF", ThreeLetterCode: "MAF", NumericCode: "663" },
    // { Name: "Saint Pierre and Miquelon", TwoLetterCode: "PM", ThreeLetterCode: "SPM", NumericCode: "666" },
    // { Name: "Saint Vincent and the Grenadines", TwoLetterCode: "VC", ThreeLetterCode: "VCT", NumericCode: "670" },
    // { Name: "Samoa", TwoLetterCode: "WS", ThreeLetterCode: "WSM", NumericCode: "882" },
    // { Name: "San Marino", TwoLetterCode: "SM", ThreeLetterCode: "SMR", NumericCode: "674" },
    // { Name: "Sao Tome and Principe", TwoLetterCode: "ST", ThreeLetterCode: "STP", NumericCode: "678" },
    // { Name: "Saudi Arabia", TwoLetterCode: "SA", ThreeLetterCode: "SAU", NumericCode: "682" },
    // { Name: "Senegal", TwoLetterCode: "SN", ThreeLetterCode: "SEN", NumericCode: "686" },
    // { Name: "Serbia", TwoLetterCode: "RS", ThreeLetterCode: "SRB", NumericCode: "688" },
    // { Name: "Seychelles", TwoLetterCode: "SC", ThreeLetterCode: "SYC", NumericCode: "690" },
    // { Name: "Sierra Leone", TwoLetterCode: "SL", ThreeLetterCode: "SLE", NumericCode: "694" },
    // { Name: "Singapore", TwoLetterCode: "SG", ThreeLetterCode: "SGP", NumericCode: "702" },
    // { Name: "Sint Maarten (Dutch part)", TwoLetterCode: "SX", ThreeLetterCode: "SXM", NumericCode: "534" },
    // { Name: "Slovakia", TwoLetterCode: "SK", ThreeLetterCode: "SVK", NumericCode: "703" },
    // { Name: "Slovenia", TwoLetterCode: "SI", ThreeLetterCode: "SVN", NumericCode: "705" },
    // { Name: "Solomon Islands", TwoLetterCode: "SB", ThreeLetterCode: "SLB", NumericCode: "090" },
    // { Name: "Somalia", TwoLetterCode: "SO", ThreeLetterCode: "SOM", NumericCode: "706" },
    // { Name: "South Africa", TwoLetterCode: "ZA", ThreeLetterCode: "ZAF", NumericCode: "710" },
    // { Name: "South Georgia and the South Sandwich Islands", TwoLetterCode: "GS", ThreeLetterCode: "SGS", NumericCode: "239" },
    // { Name: "South Sudan", TwoLetterCode: "SS", ThreeLetterCode: "SSD", NumericCode: "728" },
    // { Name: "Spain", TwoLetterCode: "ES", ThreeLetterCode: "ESP", NumericCode: "724" },
    // { Name: "Sri Lanka", TwoLetterCode: "LK", ThreeLetterCode: "LKA", NumericCode: "144" },
    // { Name: "Sudan", TwoLetterCode: "SD", ThreeLetterCode: "SDN", NumericCode: "729" },
    // { Name: "Suriname", TwoLetterCode: "SR", ThreeLetterCode: "SUR", NumericCode: "740" },
    // { Name: "Svalbard and Jan Mayen", TwoLetterCode: "SJ", ThreeLetterCode: "SJM", NumericCode: "744" },
    // { Name: "Sweden", TwoLetterCode: "SE", ThreeLetterCode: "SWE", NumericCode: "752" },
    // { Name: "Switzerland", TwoLetterCode: "CH", ThreeLetterCode: "CHE", NumericCode: "756" },
    // { Name: "Syrian Arab Republic", TwoLetterCode: "SY", ThreeLetterCode: "SYR", NumericCode: "760" },
    // { Name: "Taiwan, Province of China", TwoLetterCode: "TW", ThreeLetterCode: "TWN", NumericCode: "158" },
    // { Name: "Tajikistan", TwoLetterCode: "TJ", ThreeLetterCode: "TJK", NumericCode: "762" },
    // { Name: "Tanzania, United Republic of", TwoLetterCode: "TZ", ThreeLetterCode: "TZA", NumericCode: "834" },
    // { Name: "Thailand", TwoLetterCode: "TH", ThreeLetterCode: "THA", NumericCode: "764" },
    // { Name: "Timor-Leste", TwoLetterCode: "TL", ThreeLetterCode: "TLS", NumericCode: "626" },
    // { Name: "Togo", TwoLetterCode: "TG", ThreeLetterCode: "TGO", NumericCode: "768" },
    // { Name: "Tokelau", TwoLetterCode: "TK", ThreeLetterCode: "TKL", NumericCode: "772" },
    // { Name: "Tonga", TwoLetterCode: "TO", ThreeLetterCode: "TON", NumericCode: "776" },
    // { Name: "Trinidad and Tobago", TwoLetterCode: "TT", ThreeLetterCode: "TTO", NumericCode: "780" },
    // { Name: "Tunisia", TwoLetterCode: "TN", ThreeLetterCode: "TUN", NumericCode: "788" },
    // { Name: "Turkey", TwoLetterCode: "TR", ThreeLetterCode: "TUR", NumericCode: "792" },
    // { Name: "Turkmenistan", TwoLetterCode: "TM", ThreeLetterCode: "TKM", NumericCode: "795" },
    // { Name: "Turks and Caicos Islands", TwoLetterCode: "TC", ThreeLetterCode: "TCA", NumericCode: "796" },
    // { Name: "Tuvalu", TwoLetterCode: "TV", ThreeLetterCode: "TUV", NumericCode: "798" },
    // { Name: "Uganda", TwoLetterCode: "UG", ThreeLetterCode: "UGA", NumericCode: "800" },
    // { Name: "Ukraine", TwoLetterCode: "UA", ThreeLetterCode: "UKR", NumericCode: "804" },
    // { Name: "United Arab Emirates", TwoLetterCode: "AE", ThreeLetterCode: "ARE", NumericCode: "784" },
    // { Name: "United Kingdom of Great Britain and Northern Ireland", TwoLetterCode: "GB", ThreeLetterCode: "GBR", NumericCode: "826" },
    // { Name: "United States of America", TwoLetterCode: "US", ThreeLetterCode: "USA", NumericCode: "840" },
    // { Name: "United States Minor Outlying Islands", TwoLetterCode: "UM", ThreeLetterCode: "UMI", NumericCode: "581" },
    // { Name: "Uruguay", TwoLetterCode: "UY", ThreeLetterCode: "URY", NumericCode: "858" },
    // { Name: "Uzbekistan", TwoLetterCode: "UZ", ThreeLetterCode: "UZB", NumericCode: "860" },
    // { Name: "Vanuatu", TwoLetterCode: "VU", ThreeLetterCode: "VUT", NumericCode: "548" },
    // { Name: "Venezuela, Bolivarian Republic of", TwoLetterCode: "VE", ThreeLetterCode: "VEN", NumericCode: "862" },
    // { Name: "Viet Nam", TwoLetterCode: "VN", ThreeLetterCode: "VNM", NumericCode: "704" },
    // { Name: "Virgin Islands, British", TwoLetterCode: "VG", ThreeLetterCode: "VGB", NumericCode: "092" },
    // { Name: "Virgin Islands, U.S.", TwoLetterCode: "VI", ThreeLetterCode: "VIR", NumericCode: "850" },
    // { Name: "Wallis and Futuna", TwoLetterCode: "WF", ThreeLetterCode: "WLF", NumericCode: "876" },
    // { Name: "Western Sahara", TwoLetterCode: "EH", ThreeLetterCode: "ESH", NumericCode: "732" },
    // { Name: "Yemen", TwoLetterCode: "YE", ThreeLetterCode: "YEM", NumericCode: "887" },
    // { Name: "Zambia", TwoLetterCode: "ZM", ThreeLetterCode: "ZMB", NumericCode: "894" },
    // { Name: "Zimbabwe", TwoLetterCode: "ZW", ThreeLetterCode: "ZWE", NumericCode: "716" },
    // { Name: "Åland Islands", TwoLetterCode: "AX", ThreeLetterCode: "ALA", NumericCode: "248" }
];

// Helper function to find country by numeric code
export const findCountryByNumericCode = (numericCode: string): ISO3166Country | undefined => {
    return ISO3166Countries.find(country => country.NumericCode === numericCode);
};

// Helper function to find country by name
export const findCountryByName = (name: string): ISO3166Country | undefined => {
    return ISO3166Countries.find(country => country.Name === name);
};

// Helper function to find country by two-letter code
export const findCountryByTwoLetterCode = (code: string): ISO3166Country | undefined => {
    return ISO3166Countries.find(country => country.TwoLetterCode === code);
};

// Nigerian States
export interface NigerianState {
    name: string;
    code: string;
}

export const NigerianStates: NigerianState[] = [
    { name: "Abia", code: "AB" },
    { name: "Adamawa", code: "AD" },
    { name: "Akwa Ibom", code: "AK" },
    { name: "Anambra", code: "AN" },
    { name: "Bauchi", code: "BA" },
    { name: "Bayelsa", code: "BY" },
    { name: "Benue", code: "BE" },
    { name: "Borno", code: "BO" },
    { name: "Cross River", code: "CR" },
    { name: "Delta", code: "DE" },
    { name: "Ebonyi", code: "EB" },
    { name: "Edo", code: "ED" },
    { name: "Ekiti", code: "EK" },
    { name: "Enugu", code: "EN" },
    { name: "Federal Capital Territory", code: "FC" },
    { name: "Gombe", code: "GO" },
    { name: "Imo", code: "IM" },
    { name: "Jigawa", code: "JI" },
    { name: "Kaduna", code: "KD" },
    { name: "Kano", code: "KN" },
    { name: "Katsina", code: "KT" },
    { name: "Kebbi", code: "KE" },
    { name: "Kogi", code: "KO" },
    { name: "Kwara", code: "KW" },
    { name: "Lagos", code: "LA" },
    { name: "Nasarawa", code: "NA" },
    { name: "Niger", code: "NI" },
    { name: "Ogun", code: "OG" },
    { name: "Ondo", code: "ON" },
    { name: "Osun", code: "OS" },
    { name: "Oyo", code: "OY" },
    { name: "Plateau", code: "PL" },
    { name: "Rivers", code: "RI" },
    { name: "Sokoto", code: "SO" },
    { name: "Taraba", code: "TA" },
    { name: "Yobe", code: "YO" },
    { name: "Zamfara", code: "ZA" }
];
